### PR TITLE
fix for modeler crashes and updated status for da controller

### PR DESCRIPTION
**Pull request by dougsyer**
Hi Egor,

I'm new to github but I hope this helps, cleaned up some thing I found.

the expansion controller modeler crashes on some dell servers because
there is no slot# in the array controller mib subtree.  fixed problem
where component status was incorrect, we found many controllers showing
as offline for dell servers, i checked the mib for the battery and raid
controller and I think these work well.  tested against the 70 or so
dell servers we monitor.

### CODE REVIEW

**Comment by epuzanov** [comment]
Thank you for pointing that out. But, please next time use a LF instead of CRLF as strings delimiter.

**Comment by dougsyer** [comment]
Sorry, sloppy paste there…we love your zenpacks, thanks again!!

I haven’t tried the om.slot = str(cntlr.get('slot')).isdigit() and int(cntlr['slot']) to see if it will guard against a key error where there is no cntlr(‘slot’) at all.

The problem I was seeing was that there was no slot entry (key or value) when I did the snmp walk on the Dell server…so I was getting a key error.  I saw this on 10 or so servers, across different clients, the server and PERC controller models are all over the place.  Not sure if it’s a bug with firmware or open manage or what…

You can see the slot= in the walk through the mib tree with the pci enumerations(.1.3.6.1.4.1.674.10892.1.1100.80.1) but not the tree with the controller(.1.3.6.1.4.1.674.10893.1.20.130.1.1)..I was thinking of re-writing it to grab the slot number from the PCI slot enumeration but then decided ‘0’ was good enough.  But now, I think I can see two servers where there are more than one raid controller with no slot number, I have to look into that more though.

Doug

**Comment by epuzanov** [comment]
Hi Doug,

python' dict object has safe method 'get' if dictionary doesn't has key, get method returned None, so you can try this in python interpretor:

slot = str({}.get('key1')).isdigit() and int({}['key1']) or 0

returned slot=0

slot = str({'key1':'10'}.get('key1')).isdigit() and int({'key1':'10'}['key1']) or 0

returned slot=10

'and' 'or' construct works like a:

if  str({}.get('key1')).isdigit():
    slot = int({}['key1'])
else:
    slot = 0

PS: i like python!

**Comment by dougsyer** [comment]
Thanks, yes python is awesome, glad to get tips from the master!!.

I'll let you know if I find that there are Dell servers with two raid controllers and no slot info.  I will try to take a crack at the code first.

I  have some other fixes for hpmon and cisco mon that I will try to share soon.

Thanks again

Doug

Sent from my iPhone

On Oct 4, 2012, at 4:28 PM, "Egor Puzanov" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Doug,

python' dict object has safe method 'get' if dictionary doesn't has key, get method returned None, so you can try this in python interpretor:

slot = str({}.get('key1')).isdigit() and int({}['key1']) or 0

returned slot=0

slot = str({'key1':'10'}.get('key1')).isdigit() and int({'key1':'10'}['key1']) or 0

returned slot=10

'and' 'or' construct works like a:

if str({}.get('key1')).isdigit():
slot = int({}['key1'])
else:
slot = 0

PS: i like python!

—
Reply to this email directly or view it on GitHubhttps://github.com/epuzanov/ZenPacks.community.DellMon/pull/2#issuecomment-9155916.

---

Note: This message and any attachments is intended solely for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, legally privileged, confidential, and/or exempt from disclosure. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the original sender immediately by telephone or return email and destroy or delete this message along with any attachments immediately.

**Pull request closed without merging**
